In [11]:
import torch
import torch.nn as nn
from torch.autograd import Variable
import torch.nn.functional as F

In [2]:
x = [[1, 2, 3, 4], [3, 2, 1, 0], [2, 0, 0, 0]]
mask = [[1, 1, 1, 1], [1, 1, 1, 0], [1, 0, 0, 0]]

x = torch.LongTensor(x)
mask = torch.FloatTensor(mask)

In [3]:
x = Variable(x)
mask = Variable(mask)

In [4]:
embed = nn.Embedding(5, 10)(x)
embed.size()

torch.Size([3, 4, 10])

In [8]:
mask_count = mask.sum(1)
mask_count = mask_count.unsqueeze(1).expand([3, 10])

mask4fill = abs(mask - 1).byte()
mask4fill =mask4fill.unsqueeze(2).expand([3, 4, 10])

word_vec = embed.masked_fill_(mask4fill, 0)
word_vec.size()

torch.Size([3, 4, 10])

In [9]:
word_vec

tensor([[[-0.5498,  0.6635, -0.3239,  0.3749, -2.3261, -0.2083, -0.3730,
          -0.0145,  0.1888, -0.6171],
         [ 1.7182, -1.4283, -0.2095, -0.7118, -0.3867, -0.7100,  0.9444,
           0.0541,  1.4548, -0.1341],
         [-0.6285,  0.2084, -0.2682,  0.1283,  1.0689, -0.6030,  0.6028,
           0.1246, -0.6321, -1.7527],
         [-1.0268, -0.0342,  0.8727, -0.1280,  0.4717,  0.8876,  1.6458,
           0.3406, -0.3214, -0.1299]],

        [[-0.6285,  0.2084, -0.2682,  0.1283,  1.0689, -0.6030,  0.6028,
           0.1246, -0.6321, -1.7527],
         [ 1.7182, -1.4283, -0.2095, -0.7118, -0.3867, -0.7100,  0.9444,
           0.0541,  1.4548, -0.1341],
         [-0.5498,  0.6635, -0.3239,  0.3749, -2.3261, -0.2083, -0.3730,
          -0.0145,  0.1888, -0.6171],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
           0.0000,  0.0000,  0.0000]],

        [[ 1.7182, -1.4283, -0.2095, -0.7118, -0.3867, -0.7100,  0.9444,
           0.0541,  1.4548, -0.1341

In [12]:
avg = F.avg_pool2d(input=word_vec, kernel_size=(3, 1), stride=1) 

In [14]:
hier_sum = F.avg_pool2d(input=word_vec, kernel_size=(3, 1), stride=1) * 3
hier_count = F.avg_pool2d(input=mask.unsqueeze(2), kernel_size=(3, 1), stride=1) * 3 + 1e-8
hier_avg = torch.div(hier_sum, hier_count)

In [16]:
hier_avg

tensor([[[ 0.1800, -0.1855, -0.2672, -0.0695, -0.5480, -0.5071,  0.3914,
           0.0547,  0.3372, -0.8346],
         [ 0.0210, -0.4181,  0.1317, -0.2372,  0.3846, -0.1418,  1.0643,
           0.1731,  0.1671, -0.6722]],

        [[ 0.1800, -0.1855, -0.2672, -0.0695, -0.5480, -0.5071,  0.3914,
           0.0547,  0.3372, -0.8346],
         [ 0.5842, -0.3824, -0.2667, -0.1685, -1.3564, -0.4591,  0.2857,
           0.0198,  0.8218, -0.3756]],

        [[ 1.7182, -1.4283, -0.2095, -0.7118, -0.3867, -0.7100,  0.9444,
           0.0541,  1.4548, -0.1341],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
           0.0000,  0.0000,  0.0000]]])

In [19]:
avg

tensor([[[ 0.1800, -0.1855, -0.2672, -0.0695, -0.5480, -0.5071,  0.3914,
           0.0547,  0.3372, -0.8346],
         [ 0.0210, -0.4181,  0.1317, -0.2372,  0.3846, -0.1418,  1.0643,
           0.1731,  0.1671, -0.6722]],

        [[ 0.1800, -0.1855, -0.2672, -0.0695, -0.5480, -0.5071,  0.3914,
           0.0547,  0.3372, -0.8346],
         [ 0.3895, -0.2549, -0.1778, -0.1123, -0.9042, -0.3061,  0.1905,
           0.0132,  0.5479, -0.2504]],

        [[ 0.5727, -0.4761, -0.0698, -0.2373, -0.1289, -0.2367,  0.3148,
           0.0180,  0.4849, -0.0447],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
           0.0000,  0.0000,  0.0000]]])

In [ ]:
hier_avg.max(1)[0]

In [20]:
hier_count

tensor([[[ 3.0000e+00],
         [ 3.0000e+00]],

        [[ 3.0000e+00],
         [ 2.0000e+00]],

        [[ 1.0000e+00],
         [ 1.0000e-08]]])